# Generated by Django 3.2.5 on 2021-10-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=500)),
                ('addressline1', models.TextField()),
                ('addressline2', models.TextField()),
                ('city', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=200)),
                ('zip_code', models.IntegerField()),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
